# HW 2 scratch paper


# Q1
To create function, and create necessary structure of matrix for test purpose.

In [148]:
import numpy as np
q3 = [[1,-3,4,7],[0,1,2,2],[0,0,1,5]]
arry1 = np.array(q3)

q4 = [[1,0,8,-5,6],[0,1,4,-9,3],[0,0,1,1,2]]
arry2 = np.array(q4)

q5 = [[1,-3,7,1],[0,1,4,0],[0,0,0,5]]
arry3 = np.array(q5)

q6 = [[1,0,0,-3],[0,1,0,0],[0,0,1,5]]
arry4 = np.array(q6)

q7 = [[2,2,2,0],[-2,5,2,1],[8,1,4,1]]
arry5 = np.array(q7)

q8 = [[1,2,3,4,6], [1,2,5,2,-2], [1,1,5,5,1], [1,4,1,5,0]]
arry6 = np.array(q8)

print(arry1,"\n",arry2,"\n",arry3,"\n",arry4,"\n",arry5)

print("try to solve for the test matrix arry6")
sol = np.linalg.solve(arry6[:,:-1],arry6[:,3])

print(np.linalg.matrix_rank(arry6[:,:-1]))

print(arry6[:,:-1])

arry6

[[ 1 -3  4  7]
 [ 0  1  2  2]
 [ 0  0  1  5]] 
 [[ 1  0  8 -5  6]
 [ 0  1  4 -9  3]
 [ 0  0  1  1  2]] 
 [[ 1 -3  7  1]
 [ 0  1  4  0]
 [ 0  0  0  5]] 
 [[ 1  0  0 -3]
 [ 0  1  0  0]
 [ 0  0  1  5]] 
 [[ 2  2  2  0]
 [-2  5  2  1]
 [ 8  1  4  1]]
try to solve for the test matrix arry6
4
[[1 2 3 4]
 [1 2 5 2]
 [1 1 5 5]
 [1 4 1 5]]


array([[ 1,  2,  3,  4,  6],
       [ 1,  2,  5,  2, -2],
       [ 1,  1,  5,  5,  1],
       [ 1,  4,  1,  5,  0]])

In [134]:
#try doing a row swap
print(arry1)
#swap row 1 with row 2
co = np.copy(arry1[0])
arry1[0]=arry1[1]
arry1[1]=co
print(arry1)
print(co)

co = arry1[1]
co

[[ 1 -3  4  7]
 [ 0  1  2  2]
 [ 0  0  1  5]]
[[ 0  1  2  2]
 [ 1 -3  4  7]
 [ 0  0  1  5]]
[ 1 -3  4  7]


array([ 1, -3,  4,  7])

In [29]:
#Try the slicing or subsetting the np.array commands.
arry1[0]
# array[i] return the i row.
arry1[0][0]
# [i][i] return the i,i entry in a array.
arry1[1:,0]
# [:,i] return the i column.
np.shape(arry1)
# np.shape(A) return the m,n in a tuple.
type(np.shape(arry1))
#check the type of return.
for i in arry1:
    print(i)
    print(type(i))
# this for-each will iterate line by line, i is a np.ndarray that represent a row.
arry1[0] 

[ 1 -3  4  7]
<class 'numpy.ndarray'>
[0 1 2 2]
<class 'numpy.ndarray'>
[0 0 1 5]
<class 'numpy.ndarray'>


array([ 1, -3,  4,  7])

In [57]:
copy = np.copy(arry1)
-copy[1,0]/copy[0,0]
print(copy)
copy[:,:-1]
np.shape(copy)[0]
print(np.linalg.matrix_rank(copy)==True)

[[ 1 -3  4  7]
 [ 0  1  2  2]
 [ 0  0  1  5]]
False


In [147]:
#Write out the forward elimination algorithm function:
def REF_basic(B):
    #get the coefficient matrix Bcof from augmented matrix B.
    Bcof = B[:,:-1]
    print(Bcof)
    #check invertibility of Bcof by compare #row and #columns, and see if the rank is full.
    if (np.shape(Bcof)[0] != np.shape(Bcof)[1]) or (np.linalg.matrix_rank(Bcof) != np.shape(Bcof)[0]):
        print("Matrix B is not invertible. Bad input!")
        return 
    else:
        #use a for loop to iterate all the rows
        nrows = np.shape(B)[0]
        for i in range(nrows):
            #Use a variable sign to siginal the forward elimination process is done.
            sign = True
            while(sign):
                #check the zero in 1st element in i.
                pivot = B[i,i]
                if(pivot != 0):
                    #print("The pivot now is",i,"in the",i,"entry of diagonal.")
                    if i == (nrows-1):
                        print("we reach the last pivot, time to go home!")
                        break
                    #doing elimination.
                    print("start forward elimination for",i+1,"th column")
                    for ii in range(i+1,nrows):
                        B[ii] = (-B[ii,i]/B[i,i])*B[i]+B[ii]
                        #print("The row below pivot becomes:",B[ii])
                    #print("For pivot in",i,"column, the elimination yields:",B)
                    sign=False
                else:
                    #find non-zero entry below and do swap if it is possible.
                    for ii in range(i+1,nrows): 
                        #start one row below ith row, move up all the non-zero entries.
                        if B[ii,i]!=0:
                            
                            #swap row ii with i.
                            container = np.copy(B[ii-1]) #use container to store row i
                            B[ii-1] = B[ii]     #replace row i with new row
                            B[ii] = container# put container into new row
                            
                            #print("Finish swap row",ii,'with',ii-1,"in the iteration:",i)
                            break
                            #We only need one swap.
                        #if row ii reach the end ie ii=nrows-1, print error message. ie:"the ith column is zero column."
                        else:
                            if(ii==nrows-1):
                                print("Error: the",i,"th column is zero column.")
                                break
                            else:
                                continue
    return(B)

In [86]:
REF_basic(arry1)
print(arry1)
print("----")
REF_basic(arry2)
print(arry2)
print("----")
REF_basic(arry3)
print(arry3)
print("----")
REF_basic(arry4)
print(arry4)
print("----")
REF_basic(arry5)
print(arry5)

The row below pivot becomes: [0 1 2 2]
The row below pivot becomes: [0 0 1 5]
The row below pivot becomes: [0 0 1 5]
we reach the last pivot, time to go home!
[[ 1 -3  4  7]
 [ 0  1  2  2]
 [ 0  0  1  5]]
----
Matrix B is not invertible. Bad input!
3
[[ 1  0  8 -5  6]
 [ 0  1  4 -9  3]
 [ 0  0  1  1  2]]
----
Matrix B is not invertible. Bad input!
2
[[ 1 -3  7  1]
 [ 0  1  4  0]
 [ 0  0  0  5]]
----
The row below pivot becomes: [0 1 0 0]
The row below pivot becomes: [0 0 1 5]
The row below pivot becomes: [0 0 1 5]
we reach the last pivot, time to go home!
[[ 1  0  0 -3]
 [ 0  1  0  0]
 [ 0  0  1  5]]
----
Matrix B is not invertible. Bad input!
2
[[ 2  2  2  0]
 [-2  5  2  1]
 [ 8  1  4  1]]


In [164]:
print(arry6)
REF_basic(arry6)
print(arry6)
print(arry6[:,-1])

[[ 1  2  3  4  6]
 [ 0 -1  2  1 -5]
 [ 0  0  2 -2 -8]
 [ 0  0  0  5 -8]]
[[ 1  2  3  4]
 [ 0 -1  2  1]
 [ 0  0  2 -2]
 [ 0  0  0  5]]
The pivot now is 0 in the 0 entry of diagonal.
The row below pivot becomes: [ 0 -1  2  1 -5]
The row below pivot becomes: [ 0  0  2 -2 -8]
The row below pivot becomes: [ 0  0  0  5 -8]
For pivot in 0 column, the elimination yields: [[ 1  2  3  4  6]
 [ 0 -1  2  1 -5]
 [ 0  0  2 -2 -8]
 [ 0  0  0  5 -8]]
The pivot now is 1 in the 1 entry of diagonal.
The row below pivot becomes: [ 0  0  2 -2 -8]
The row below pivot becomes: [ 0  0  0  5 -8]
For pivot in 1 column, the elimination yields: [[ 1  2  3  4  6]
 [ 0 -1  2  1 -5]
 [ 0  0  2 -2 -8]
 [ 0  0  0  5 -8]]
The pivot now is 2 in the 2 entry of diagonal.
The row below pivot becomes: [ 0  0  0  5 -8]
For pivot in 2 column, the elimination yields: [[ 1  2  3  4  6]
 [ 0 -1  2  1 -5]
 [ 0  0  2 -2 -8]
 [ 0  0  0  5 -8]]
The pivot now is 3 in the 3 entry of diagonal.
we reach the last pivot, time to go home!


In [113]:
#Try to clean a array
a=[1,2]
b=a
a=[]
print(a,b)

a = [1,2]
b = a
del a[:]
print(a,b)

[] [1, 2]
[] []


## Q2

In [153]:
def REF(B):
    #Given any size of matrix, conduct the forward elimination.
    #use a for loop to iterate all the rows
    nrows = np.shape(B)[0]
    for i in range(nrows):
        #Use a variable sign to siginal the forward elimination process is done.
        sign = True
        while(sign):
            #check the zero in 1st element in i.
            pivot = B[i,i]
            if(B[i,i]!=0):
                print("The pivot now is",i,"in the",i,"entry of diagonal.")
                if i == (nrows-1):
                    print("we reach the last pivot, time to go home!")
                    print("The B is this",B)
                    break
                #doing elimination.
                for ii in range(i+1,nrows):
                    B[ii] = (-B[ii,i]/B[i,i])*B[i]+B[ii]
                    print("The row below pivot becomes:",B[ii])
                print("For pivot in",i,"column, the elimination yields:",B)
                sign=False
            else:
                #find non-zero entry below and do swap if it is possible.
                for ii in range(i+1,nrows): 
                    #start one row below ith row, move up all the non-zero entries.
                    if B[ii,i]!=0:
                        print("We find a pivot candidate!!!,it is the",ii,"th row")
                        #swap row ii with i.
                        container = np.copy(B[ii-1]) #use container to store row i
                        B[ii-1] = B[ii]     #replace row i with new row
                        B[ii] = container# put container into new row
                        print("Container is :",container)
                        print("Finish swap row",ii,'with',ii-1,"in the iteration:",i)
                        break
                        #clear out container
                        #We only need one swap.
                    #if row ii reach the end ie ii=nrows-1, print error message. ie:"the ith column is zero column."
                    else:
                        if(ii==nrows-1):
                            print("Error: the",i,"th column is zero column.")
                            break
                        else:
                            continue
    return B

In [163]:
q3 = [[1,-3,4,7],[0,1,2,2],[0,0,1,5]]
arry1 = np.array(q3)
REF(arry1)

q8 = [[1,2,3,4,6], [1,2,5,2,-2], [1,1,5,5,1], [1,4,1,5,0]]
arry6 = np.array(q8)
REF(arry6)

aug1 = np.column_stack((arry6,np.array([1,2,3,4])))
print(aug1)

The pivot now is 0 in the 0 entry of diagonal.
The row below pivot becomes: [0 1 2 2]
The row below pivot becomes: [0 0 1 5]
For pivot in 0 column, the elimination yields: [[ 1 -3  4  7]
 [ 0  1  2  2]
 [ 0  0  1  5]]
The pivot now is 1 in the 1 entry of diagonal.
The row below pivot becomes: [0 0 1 5]
For pivot in 1 column, the elimination yields: [[ 1 -3  4  7]
 [ 0  1  2  2]
 [ 0  0  1  5]]
The pivot now is 2 in the 2 entry of diagonal.
we reach the last pivot, time to go home!
The B is this [[ 1 -3  4  7]
 [ 0  1  2  2]
 [ 0  0  1  5]]
The pivot now is 0 in the 0 entry of diagonal.
The row below pivot becomes: [ 0  0  2 -2 -8]
The row below pivot becomes: [ 0 -1  2  1 -5]
The row below pivot becomes: [ 0  2 -2  1 -6]
For pivot in 0 column, the elimination yields: [[ 1  2  3  4  6]
 [ 0  0  2 -2 -8]
 [ 0 -1  2  1 -5]
 [ 0  2 -2  1 -6]]
We find a pivot candidate!!!,it is the 2 th row
Container is : [ 0  0  2 -2 -8]
Finish swap row 2 with 1 in the iteration: 1
The pivot now is 1 in th

## Q3


In [173]:
# create some randomly generated matrix that is square matrix. 
#  reuse function from hw1 to create such matrix.
def R(echelon):
    mean = 0
    var = echelon**2
    matrixNoise = np.random.normal(mean,var,(10,10))
    return matrixNoise
#make one matrix with standard deviation 0.2.
matrixNoise = R(0.2)
b = np.matrix.transpose(np.ones(10))
type(b)

numpy.ndarray

In [178]:
def chkshape(array):
    #write a new function: chkshape(array). Output -1 means error; 1 it is square; 0 it is rectangle.
    if np.ndim(array) != 2:
        print("Error, the matrix is not 2-Dimension.")
        return -1
    else:
        shape = np.shape(array)
        if (shape[0]-shape[1]) == 0:
            return 1
        else: 
            return 0

        
def checkUpper(array):
    #write a function to check the upper triangle property of any given matrix.
    #Output: True as upper tirangle shape, False as not upper triangle shape.
    #Learned from [https://www.geeksforgeeks.org/program-check-matrix-upper-triangular/]
    #This should be done after confirmation of being square matrix.
    dim = np.shape(array)[0]
    for i in range(1,dim):
        for j in range(0,i):
            if array[i][j]!=0:
                return False
    return True
        
#Compute the unknowns by backward substitution.
#Learned from [https://codereview.stackexchange.com/questions/110039/back-substitution-method-for-solving-linear-system]
def backsub(array,vector):
    if chkshape(array) !=1:
        if chkshape(array) == 0:
            print("Error message: Matrix\n",array," \nis rectangle. ")
            return
    else:
        if checkUpper(array) == False:
            print("Error message: Matrix's shape is not upper-triangle.\n","Please re-enter your matrix")
            return
    ls = np.zeros_like(vector)
    size = np.shape(vector)[0]
    
    #Find the last index's value of vector.
    for i in range(size-1,-1,-1): #index starts from n-1 to 0.
        #Check if all diagonal entries is nonzero. If it is not, then print error and return.
        if array[i,i] == 0:
            print("Error message: the diagonal entries have number 0.")
            return
        if i == size - 1:
            #Start to iterate from the bottom row, get the last entry's value.
            x = (vector[i])/array[-1,-1]
            #Then go up one row. compute the result of x(index) by using what is stored in the result list(ls).
        else:
            #compute the result of x(index).
            x = (vector[i]-np.sum(array[i,i+1:] * ls[i+1:]))/array[i,i]
        #store the value of unknown into ls, with index starting backward. ie: xn,xn-1,...,x2,x1
        ls[i]=x
    print(ls)
 

def MySolve(A,b):
    #do the foward elimination first. A is n*n, b is n*1
    aug = np.column_stack((A,b))
    #Forward elimination result.
    uRes = REF_basic(aug)
    #Then get the coefficient matrix, and constant after forward elimination to do the back substitution.
    cof = aug[:,:-1]
    const = aug[:,-1]
    backsub(cof,const)
    return "Finish solving Ax=b."

In [179]:
MySolve(matrixNoise,b)
print("\n------\n")
MySolve(arry1[:,:-1],arry1[:,-1])

[[ 4.97620311e-02 -2.16468695e-03 -1.81464158e-02  1.30597224e-02
   6.44874474e-02  4.22461852e-02 -2.57698795e-02  1.12687935e-02
  -1.04303926e-01  2.99383764e-02]
 [-4.32816652e-02 -3.57810070e-02  3.97931216e-02 -5.40909078e-02
   1.55315545e-02 -8.66862177e-03  2.69523892e-03  2.13279501e-02
  -3.54144329e-02 -3.51173659e-02]
 [-2.23156301e-02  1.29738295e-02 -1.67374258e-02 -4.40591884e-02
  -1.74995104e-02 -1.13655076e-02  7.69769996e-02  7.82318623e-02
  -1.35794237e-02 -4.67416848e-02]
 [-3.71534404e-02  6.11935052e-02  1.27977153e-02  1.70992258e-05
   3.36099876e-02  3.54046344e-03  6.51833345e-02 -1.22695696e-02
   6.86475762e-02 -3.32774375e-02]
 [-3.86657917e-02  5.02896770e-02  3.62681936e-02  2.89324197e-02
  -2.19617624e-02 -1.88311960e-02 -2.33318792e-02  4.27924916e-02
  -3.78613048e-02  7.93652526e-02]
 [ 1.00981689e-01  4.55919660e-02 -1.76523246e-02 -6.75741711e-03
   6.78625163e-02 -3.82321644e-03  4.05295949e-02  5.95992343e-02
   3.71987461e-02 -1.55235686e-02

'Finish solving Ax=b.'

In [183]:
#generate random values in fixed size of matrix
rdMat = np.random.rand(10,10)
print(rdMat,"\n",b)
np.linalg.solve(rdMat,b)


[[0.65280516 0.30617927 0.88120121 0.927944   0.02228425 0.40207509
  0.7649635  0.70326427 0.43243946 0.0029314 ]
 [0.22583702 0.0532153  0.41997779 0.10256191 0.16789295 0.25067506
  0.13611006 0.39853132 0.42576337 0.68714554]
 [0.30996034 0.98671671 0.45989529 0.26530041 0.30327895 0.25432963
  0.61251736 0.78365465 0.46335681 0.38075655]
 [0.14429285 0.091151   0.17527535 0.44874655 0.32462318 0.80461282
  0.68780603 0.94099727 0.02413681 0.47455288]
 [0.77496868 0.85932585 0.69021111 0.87824128 0.04156659 0.6443098
  0.24891051 0.45795745 0.59363442 0.81681914]
 [0.13073638 0.83661006 0.00173492 0.16759148 0.15462804 0.16633151
  0.30049102 0.10467056 0.82379568 0.68960317]
 [0.70197202 0.15635053 0.21110698 0.10704201 0.17062335 0.6064723
  0.91620602 0.38694636 0.33331075 0.35007823]
 [0.49881209 0.88717159 0.90538541 0.94484306 0.387972   0.46646194
  0.08625531 0.07552666 0.93929322 0.61811554]
 [0.59199344 0.36728203 0.99906027 0.90218576 0.70951474 0.43458867
  0.11047136 0

array([ 0.2247834 , -0.27862428, -0.43246818, -3.09585818, -2.2613565 ,
        5.35246806, -3.67367709,  3.4282734 ,  5.78590962, -4.11635634])

In [188]:
import math
math.log(3,2)
type(np.random.rand(10))

numpy.ndarray