## Start of Homework Answer
### Question A
Familiarize yourself with the numpy.linalg package. Define a 10 × 10 matrix A whose entries are
the numbers from 1 to 100 ordered consecutively going across rows (so a1,1 = 1, a2,1 = 11, a10,1 = 91,
etc). Let v = (1, 2, ...10), and b = (1, 1, ...1). Compute Av and solve Ax = b and Ax = v using
linalg.solve. Verify your solution by computing Ax.

In [2]:
#CREATE A 10 BY 10 MATRIX CALLED matrixA.
import numpy as np

matrixA=np.arange(1,101,1).reshape(10,10)

#DEFINE VECTOR V AND B.
v = np.arange(1,11)
b = np.ones(10)

#SHOW THE SHAPE OF A,V,B.
print("matrix A is\n",matrixA)
print("vector v and b are:\n",v,' ;',b)

#COMPUTE THE Av.
Av = np.dot(matrixA,v)
print("The result of Av is:\n",Av)

#SOLVE THE AX=B AND AX=V.
x1 = np.linalg.solve(matrixA,b)
x2 = np.linalg.solve(matrixA,v)

print(np.dot(matrixA,x1))
print(np.dot(matrixA,x2))

matrix A is
 [[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
vector v and b are:
 [ 1  2  3  4  5  6  7  8  9 10]  ; [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
The result of Av is:
 [ 385  935 1485 2035 2585 3135 3685 4235 4785 5335]


LinAlgError: Singular matrix

### Question B
You may get some error in doing above. You decide to “shake” your matrix by some noise, after all data usual comes in noisy. Use the numpy.random package to build a 10×10 matrix R(ε) whose entries are i.i.d. Gaussian random variables that follow N(0,ε2). Verify now that you “can” compute the questions above for various values of ε > 0 for the new matrix A + R(ε).

In [3]:
#CONSTRUCT THE NOISE MATRIX.
def R(echelon):
    mean = 0
    var = echelon**2
    matrixNoise = np.random.normal(mean,var,(10,10))
    return matrixNoise
matrixNoise = R(0.2)
print("The noise matrix is constructed by standard deviation of 0.2:\n",matrixNoise)

#COMBINE THE TWO MATRICES.
matrixNew = matrixNoise + matrixA

#SOLVE THE NEW MATRIX Ax=b and Ax=v.
x3 = np.linalg.solve(matrixNew,b)
x4 = np.linalg.solve(matrixNew,v)

#CHECK ANSWER.
print("The solution of matrix (A+R(eplison))x=b is:\n",np.dot(matrixNew,x3))
print("The solution of matrix (A+R(eplison))x=v is:\n",np.dot(matrixNew,x4))
print("The result shows that we could compute correctly now.")

The noise matrix is constructed by standard deviation of 0.2:
 [[-6.32260620e-02  1.69342866e-03  1.52064936e-02  5.54929973e-02
  -2.79170728e-03  7.80482290e-02  3.91252279e-02  1.08520412e-01
  -8.14291866e-04 -1.94081981e-02]
 [-1.83586046e-02 -4.97101437e-02  5.81691906e-02 -3.81874628e-02
   2.58370248e-02  3.82352691e-02 -5.63126121e-02 -3.77832467e-02
  -3.65874668e-02  1.81629416e-03]
 [ 2.79056920e-02 -3.56224073e-02 -4.77234759e-02 -4.10202849e-02
   3.83632266e-02  3.29724097e-02  2.61723690e-02 -3.57968697e-02
  -4.79560368e-03 -1.95494177e-02]
 [ 3.38079955e-02  4.93173637e-02  3.75959863e-02  5.39106475e-02
   1.91784791e-02  5.33805453e-02  1.67328423e-02  2.47734423e-02
  -3.49230395e-02  2.82452388e-02]
 [-2.67036681e-02  3.61785976e-02 -4.34331705e-03  4.11178106e-02
   4.46292759e-03  5.40697303e-02 -1.22911553e-02  2.91808585e-02
   4.15250143e-02  4.76389052e-03]
 [-4.77844680e-02  1.34546984e-02  7.97198862e-02 -2.64126591e-02
  -2.24809152e-02 -2.11989373e-02  1

### Question C
Write a python function BackSub(A, b) that does the backward substitution from scratch. The input A must be an upper triangular square matrix whose diagonals are all nonzero, and b must be a vector of appropriate dimension. Raise an error if inputs do not satisfy the requirements. Only 1 for loop is needed. It should return the unique solution of solving Ax = b. Test your function on
(a) Problem 3 (b) a 3 × 3 matrix that is not upper triangular (c) a 3 × 2 matrix (d) Problem 5

In [4]:
#PREPARE THE INPUT MATRIX AS REQUIRED.
#(a)matrix and vector from Problem 3.
matA = np.array([[1,-3,4],[0,1,2],[0,0,1]])
vetA = np.transpose(np.array([7,2,5]))

#(b)one lower triangle matrix.
matB = np.array([[1,2,0],[0,2,4],[3,0,0]])

#(c)a 3*2 matrix.
matC = np.array([[1,2],[3,5],[5,6]])

#(d)matrix and vector from Problem 5.
matD = np.array([[1,-3,7],[0,1,4],[0,0,0]])
vetD = np.array([1,0,5])

def chkshape(array):
    #write a new function: chkshape(array). Output -1 means error; 1 it is square; 0 it is rectangle.
    if np.ndim(array) != 2:
        print("Error, the matrix is not 2-Dimension.")
        return -1
    else:
        shape = np.shape(array)
        if (shape[0]-shape[1]) == 0:
            return 1
        else: 
            return 0

        
def checkUpper(array):
    #write a function to check the upper triangle property of any given matrix.
    #Output: True as upper tirangle shape, False as not upper triangle shape.
    #Learned from [https://www.geeksforgeeks.org/program-check-matrix-upper-triangular/]
    #This should be done after confirmation of being square matrix.
    dim = np.shape(array)[0]
    for i in range(1,dim):
        for j in range(0,i):
            if array[i][j]!=0:
                return False
    return True
        
#Compute the unknowns by backward substitution.
#Learned from [https://codereview.stackexchange.com/questions/110039/back-substitution-method-for-solving-linear-system]
def backsub(array,vector):
    if chkshape(array) !=1:
        if chkshape(array) == 0:
            print("Error message: Matrix\n",array," \nis rectangle. ")
            return
    else:
        if checkUpper(array) == False:
            print("Error message: Matrix's shape is not upper-triangle.\n","Please re-enter your matrix")
            return
    ls = np.zeros_like(vector)
    size = np.shape(vector)[0]
    
    #Find the last index's value of vector.
    for i in range(size-1,-1,-1): #index starts from n-1 to 0.
        #Check if all diagonal entries is nonzero. If it is not, then print error and return.
        if array[i,i] == 0:
            print("Error message: the diagonal entries have number 0.")
            return
        if i == size - 1:
            #Start to iterate from the bottom row, get the last entry's value.
            x = (vector[i])/array[-1,-1]
            #Then go up one row. compute the result of x(index) by using what is stored in the result list(ls).
        else:
            #compute the result of x(index).
            x = (vector[i]-np.sum(array[i,i+1:] * ls[i+1:]))/array[i,i]
        #store the value of unknown into ls, with index starting backward. ie: xn,xn-1,...,x2,x1
        ls[i]=x
    print(ls)
 
#The linear system in (a) has unique solution.
backsub(matA,vetA)
#The linear system in (b) is not in the shape of a square matrix.
backsub(matB,vetA)
#The shape of linear system in (C) is not right.
backsub(matC,vetA)
#The zero diagonal entry in matrix (D) prevent the calculation's success.
backsub(matD,vetD)

[-37  -8   5]
Error message: Matrix's shape is not upper-triangle.
 Please re-enter your matrix
Error message: Matrix
 [[1 2]
 [3 5]
 [5 6]]  
is rectangle. 
Error message: the diagonal entries have number 0.
