# HW #2: Python parts

## Question :1 

Write a python function REF basic(B) that will return the REF (pivots do not have to be 1) of any n×(n+1) augmented matrix. Row swapping should be included. Your input should be any n×(n+1) augmented matrix such that the coefficient matrix is invertible. This is how you should be checking invertibility: during the iteration process, your code should make sure every column of the coefficient matrix has a pivot. If not, then the program stops and returns an error message. Test your function at least on
(a) The augmented matrix in HW1-7 (b) np.array([[1,2,3,4,6], [1,2,5,2,-2], [1,1,5, 5,1], [1, 4, 1, 5, 0]])


In [30]:
#Write out the forward elimination algorithm function:
def REF_basic(B):
    #get the coefficient matrix Bcof from augmented matrix B.
    Bcof = B[:,:-1]
    #check invertibility of Bcof by compare #row and #columns, and see if the rank is full.
    if (np.shape(Bcof)[0] != np.shape(Bcof)[1]) or (np.linalg.matrix_rank(Bcof) != np.shape(Bcof)[0]):
        print("Matrix B is not invertible. Bad input!")
        return 
    else:
        #use a for loop to iterate all the rows
        nrows = np.shape(B)[0]
        for i in range(nrows):
            #Use a variable sign to siginal the forward elimination process is done.
            sign = True
            while(sign):
                #check the zero in 1st element in i.
                pivot = B[i,i]
                if(pivot != 0):
                    #print("The pivot now is",i,"in the",i,"entry of diagonal.")
                    if i == (nrows-1):
                        #print("we reach the last pivot, time to go home!")
                        break
                    #doing elimination.
                    #print("start forward elimination for",i+1,"th column")
                    for ii in range(i+1,nrows):
                        B[ii] = (-B[ii,i]/B[i,i])*B[i]+B[ii]
                        #print("The row below pivot becomes:",B[ii])
                    #print("For pivot in",i,"column, the elimination yields:",B)
                    sign=False
                else:
                    #find non-zero entry below and do swap if it is possible.
                    for ii in range(i+1,nrows): 
                        #start one row below ith row, move up all the non-zero entries.
                        if B[ii,i]!=0:
                            
                            #swap row ii with i.
                            container = np.copy(B[ii-1]) #use container to store row i
                            B[ii-1] = B[ii]     #replace row i with new row
                            B[ii] = container# put container into new row
                            
                            #print("Finish swap row",ii,'with',ii-1,"in the iteration:",i)
                            break
                            #We only need one swap.
                        #if row ii reach the end ie ii=nrows-1, print error message. ie:"the ith column is zero column."
                        else:
                            if(ii==nrows-1):
                                print("Error: the",i,"th column is zero column.")
                                break
                            else:
                                continue
    return(B)

In [17]:
# Construct test case:
import numpy as np
q3 = [[1,-3,4,7],[0,1,2,2],[0,0,1,5]]
arry1 = np.array(q3)

q4 = [[1,0,8,-5,6],[0,1,4,-9,3],[0,0,1,1,2]]
arry2 = np.array(q4)

q5 = [[1,-3,7,1],[0,1,4,0],[0,0,0,5]]
arry3 = np.array(q5)

q6 = [[1,0,0,-3],[0,1,0,0],[0,0,1,5]]
arry4 = np.array(q6)

q7 = [[2,2,2,0],[-2,5,2,1],[8,1,4,1]]
arry5 = np.array(q7)

q8 = [[1,2,3,4,6], [1,2,5,2,-2], [1,1,5,5,1], [1,4,1,5,0]]
arry6 = np.array(q8)

print("arry1\n",arry1,"\n\n","arry2\n",arry2,"\n\n","arry3\n",arry3,"\n\n","arry4\n",arry4,
      "\n\n","arry5\n",arry5,"\n\n","arry6\n",arry6)

arry1
 [[ 1 -3  4  7]
 [ 0  1  2  2]
 [ 0  0  1  5]] 

 arry2
 [[ 1  0  8 -5  6]
 [ 0  1  4 -9  3]
 [ 0  0  1  1  2]] 

 arry3
 [[ 1 -3  7  1]
 [ 0  1  4  0]
 [ 0  0  0  5]] 

 arry4
 [[ 1  0  0 -3]
 [ 0  1  0  0]
 [ 0  0  1  5]] 

 arry5
 [[ 2  2  2  0]
 [-2  5  2  1]
 [ 8  1  4  1]] 

 arry6
 [[ 1  2  3  4  6]
 [ 1  2  5  2 -2]
 [ 1  1  5  5  1]
 [ 1  4  1  5  0]]


In [18]:
# Carry out test.
REF_basic(arry1)
print(arry1)
print("----")
REF_basic(arry2)
print(arry2)
print("----")
REF_basic(arry3)
print(arry3)
print("----")
REF_basic(arry4)
print(arry4)
print("----")
REF_basic(arry5)
print(arry5)
print("----")
REF_basic(arry6)
print(arry6)

[[ 1 -3  4]
 [ 0  1  2]
 [ 0  0  1]]
start forward elimination for 1 th column
start forward elimination for 2 th column
we reach the last pivot, time to go home!
[[ 1 -3  4  7]
 [ 0  1  2  2]
 [ 0  0  1  5]]
----
[[ 1  0  8 -5]
 [ 0  1  4 -9]
 [ 0  0  1  1]]
Matrix B is not invertible. Bad input!
[[ 1  0  8 -5  6]
 [ 0  1  4 -9  3]
 [ 0  0  1  1  2]]
----
[[ 1 -3  7]
 [ 0  1  4]
 [ 0  0  0]]
Matrix B is not invertible. Bad input!
[[ 1 -3  7  1]
 [ 0  1  4  0]
 [ 0  0  0  5]]
----
[[1 0 0]
 [0 1 0]
 [0 0 1]]
start forward elimination for 1 th column
start forward elimination for 2 th column
we reach the last pivot, time to go home!
[[ 1  0  0 -3]
 [ 0  1  0  0]
 [ 0  0  1  5]]
----
[[ 2  2  2]
 [-2  5  2]
 [ 8  1  4]]
Matrix B is not invertible. Bad input!
[[ 2  2  2  0]
 [-2  5  2  1]
 [ 8  1  4  1]]
----
[[1 2 3 4]
 [1 2 5 2]
 [1 1 5 5]
 [1 4 1 5]]
start forward elimination for 1 th column
start forward elimination for 2 th column
start forward elimination for 3 th column
we reach th

## Question 1Extra
Write a python function REF(A) that will return the REF (pivots do not have to be 1)
of any m×n matrix A.

In [ ]:
def REF(A):
    #Given any size of matrix, conduct the forward elimination.
    #use a for loop to iterate all the rows
    nrows = np.shape(A)[0]
    for i in range(nrows):
        #Use a variable sign to siginal the forward elimination process is done.
        sign = True
        while(sign):
            #check the zero in 1st element in i.
            pivot = A[i,i]
            if(A[i,i]!=0):
                if i == (nrows-1):
                    print("The A is this",A)
                    break
                #doing elimination.
                for ii in range(i+1,nrows):
                    A[ii] = (-A[ii,i]/A[i,i])*A[i]+A[ii]
                sign=False
            else:
                #find non-zero entry below and do swap if it is possible.
                for ii in range(i+1,nrows): 
                    #start one row below ith row, move up all the non-zero entries.
                    if A[ii,i]!=0:
                        #swap row ii with i.
                        container = np.copy(A[ii-1]) #use container to store row i
                        A[ii-1] = A[ii]     #replace row i with new row
                        A[ii] = container# put container into new row
                        break
                    #if row ii reach the end ie ii=nrows-1, print error message. ie:"the ith column is zero column."
                    else:
                        if(ii==nrows-1):
                            print("Error: the",i,"th column is zero column.")
                            break
                        else:
                            continue
    return A

## Question:2
Write a python function MySolve(A, b) that will solve Ax = b if A is invertible. This should be as simple as calling functions that you have already written. Compare your function with linalg.solve on randomly generated systems to make sure that your code is working.


In [37]:
def chkshape(array):
    #write a new function: chkshape(array). Output -1 means error; 1 it is square; 0 it is rectangle.
    if np.ndim(array) != 2:
        print("Error, the matrix is not 2-Dimension.")
        return -1
    else:
        shape = np.shape(array)
        if (shape[0]-shape[1]) == 0:
            return 1
        else: 
            return 0

        
def checkUpper(array):
    #write a function to check the upper triangle property of any given matrix.
    #Output: True as upper tirangle shape, False as not upper triangle shape.
    #Learned from [https://www.geeksforgeeks.org/program-check-matrix-upper-triangular/]
    #This should be done after confirmation of being square matrix.
    dim = np.shape(array)[0]
    for i in range(1,dim):
        for j in range(0,i):
            if array[i][j]!=0:
                return False
    return True
        
#Compute the unknowns by backward substitution.
#Learned from [https://codereview.stackexchange.com/questions/110039/back-substitution-method-for-solving-linear-system]
def backsub(array,vector):
    if chkshape(array) !=1:
        if chkshape(array) == 0:
            print("Error message: Matrix\n",array," \nis rectangle. ")
            return
    else:
        if checkUpper(array) == False:
            print("Error message: Matrix's shape is not upper-triangle.\n","Please re-enter your matrix")
            return
    ls = np.zeros_like(vector)
    size = np.shape(vector)[0]
    
    #Find the last index's value of vector.
    for i in range(size-1,-1,-1): #index starts from n-1 to 0.
        #Check if all diagonal entries is nonzero. If it is not, then print error and return.
        if array[i,i] == 0:
            print("Error message: the diagonal entries have number 0.")
            return
        if i == size - 1:
            #Start to iterate from the bottom row, get the last entry's value.
            x = (vector[i])/array[-1,-1]
            #Then go up one row. compute the result of x(index) by using what is stored in the result list(ls).
        else:
            #compute the result of x(index).
            x = (vector[i]-np.sum(array[i,i+1:] * ls[i+1:]))/array[i,i]
        #store the value of unknown into ls, with index starting backward. ie: xn,xn-1,...,x2,x1
        ls[i]=x
    return ls
 

def MySolve(A,b):
    #do the foward elimination first. A is n*n, b is n*1
    aug = np.column_stack((A,b))
    #Forward elimination result.
    uRes = REF_basic(aug)
    #Then get the coefficient matrix, and constant after forward elimination to do the back substitution.
    cof = aug[:,:-1]
    const = aug[:,-1]
    return backsub(cof,const)

In [25]:
# create some randomly generated matrix that is square matrix. 
#  reuse function from hw1 to create such matrix.
def R(echelon):
    mean = 0
    var = echelon**2
    matrixNoise = np.random.normal(mean,var,(10,10))
    return matrixNoise
#make one matrix with standard deviation 0.2.

[[ 0.05584067  0.02776651 -0.01931823 -0.00177156 -0.07756582  0.01550349
   0.00461468 -0.05615392 -0.06442764 -0.01424488]
 [-0.08301078 -0.03906641 -0.04382761 -0.04584145 -0.00658121  0.00576602
  -0.01819392  0.09300944  0.02899311  0.04481143]
 [ 0.04432883  0.0215484  -0.00772872  0.00521255 -0.01788349  0.01533981
   0.00423416 -0.05046217  0.02288062 -0.00142084]
 [-0.01824372  0.01000852  0.04857559  0.01882668 -0.03812957 -0.03100675
  -0.02762878  0.01373141  0.04307958  0.02820926]
 [ 0.00626079  0.05116467 -0.05524433 -0.03739458  0.02099699 -0.06069071
   0.04624642 -0.0582746  -0.0498731   0.09839668]
 [ 0.03641859 -0.0397273  -0.02029031 -0.0520126   0.01087877  0.05156824
  -0.0206203  -0.02641812  0.0059094  -0.01561774]
 [ 0.01674465  0.06725411  0.01785163 -0.06781031 -0.05854399 -0.04934581
   0.01378598 -0.02497769 -0.03992553 -0.02004921]
 [-0.07564749 -0.00335947 -0.02394795  0.00234383  0.02292512  0.0410536
   0.01338606  0.02658706  0.06400286  0.02920501]
 

'Finish solving Ax=b.'

In [42]:
#test by using np.linalg.solve
print("Case 1: Using numpy function:linalg.solve\n",np.linalg.solve(arry1[:,:-1],arry1[:,-1]))
print("\nUsing my own algorithm\n",MySolve(arry1[:,:-1],arry1[:,-1]))

#test on noise matrix, with entries following Normal distribution.
matrixNoise = R(0.2)
b = np.ones(10)
bT = np.matrix.transpose(np.ones(10))
print("\nCase 2: Using numpy function:linalg.solve\n",np.linalg.solve(matrixNoise,b))
print("\nUsing my own algorithm:\n",MySolve(matrixNoise,bT))


#test on random generating values.
rdMat = np.random.rand(10,10)
print("\nCase 3: Using numpy function:linalg.solve\n",np.linalg.solve(rdMat,b))
print("\nUsing my own algorithm:\n",MySolve(rdMat,bT))

Case 1: Using numpy function:linalg.solve
 [-37.  -8.   5.]

Using my own algorithm
 [-37  -8   5]

Case 2: Using numpy function:linalg.solve
 [-66.06262685 -10.1419804   96.73763955  37.43248397 -32.15394944
 -97.80439944 -73.93952291 -56.99312747  -0.35224874   8.0668309 ]
Error message: Matrix's shape is not upper-triangle.
 Please re-enter your matrix

Using my own algorithm:
 None

Case 3: Using numpy function:linalg.solve
 [ 0.53103002 -0.80441179  0.66503149  1.01002972  0.28592043  0.14030103
 -0.07142997  0.06864944  0.58207783 -0.24260036]
Error message: Matrix's shape is not upper-triangle.
 Please re-enter your matrix

Using my own algorithm:
 None


## Question 4
Lets computationally test the complexity of your MySolve(A, b). Do so by doing 7 runs of random matrices of size $2^k$, for k = 0,...,10. Let Tk = average time for a matrix of size $2^k$. Plot the log2(Tk) against k. How can we tell the leading order complexity from this plot, i.e. why does this plot show exactly that?

In [54]:
import matplotlib.pyplot as plt
import time
import math as ma
k = np.array(range(11))
print(k)
Tk = np.ones(10)
lapse,SUM,stPoint = 0,0,0
for ii in k:
    #create the random matrix.
    randMat = np.random.rand(2^ii,2^ii)
    randb = np.transpose(np.random.rand(2^ii))
    print(randMat,randb)
    for i in range(7):
        #start counting time
        stPoint = time.time()
        #Try solving for an answer
        MySolve(randMat,randb)
        #count the end time.
        lapse = time.time() - stPoint
        SUM += lapse
    Tk[i] = SUM/7
for j in k:
    plt.scatter(ma.log(Tk[j],2),k[j])
    plt.show()

[ 0  1  2  3  4  5  6  7  8  9 10]
[[0.27881342 0.21995109]
 [0.05381449 0.96134181]] [0.87140703 0.38156276]
[[0.98084249 0.08170528 0.96451845]
 [0.93920403 0.63771527 0.44676378]
 [0.62144642 0.16639446 0.01130411]] [0.00295125 0.11491219 0.24225047]
[] []


LinAlgError: Arrays cannot be empty