In [1]:
import math


In [5]:
a = math.sqrt(17)*math.sqrt(26)
b = 20/a
print (b)

0.9513029883089883


In [12]:
theta= math.acos(b)
print(theta*180)

56.404923068375915


In [13]:
math.cos(56)



0.853220107722584

In [35]:
# REFERENCE OF CREATION OF MATRIX AND LINALG LIBRARY.
# https://docs.scipy.org/doc/numpy-1.13.0/user/quickstart.html

import numpy as np

matrixA=np.arange(1,101,1).reshape(10,10)
print(matrixA)

matrixA.shape
matrixA.ndim
matrixA.size
matrixA[1]

import numpy.linalg as la

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


array([[ 3355,  3410,  3465,  3520,  3575,  3630,  3685,  3740,  3795,
         3850],
       [ 7955,  8110,  8265,  8420,  8575,  8730,  8885,  9040,  9195,
         9350],
       [12555, 12810, 13065, 13320, 13575, 13830, 14085, 14340, 14595,
        14850],
       [17155, 17510, 17865, 18220, 18575, 18930, 19285, 19640, 19995,
        20350],
       [21755, 22210, 22665, 23120, 23575, 24030, 24485, 24940, 25395,
        25850],
       [26355, 26910, 27465, 28020, 28575, 29130, 29685, 30240, 30795,
        31350],
       [30955, 31610, 32265, 32920, 33575, 34230, 34885, 35540, 36195,
        36850],
       [35555, 36310, 37065, 37820, 38575, 39330, 40085, 40840, 41595,
        42350],
       [40155, 41010, 41865, 42720, 43575, 44430, 45285, 46140, 46995,
        47850],
       [44755, 45710, 46665, 47620, 48575, 49530, 50485, 51440, 52395,
        53350]])

In [83]:
#check a matrix shape

#(c)a 3*2 matrix
c = np.array([[1,2],[3,5],[5,6]])
print(np.shape(c))
shape = np.shape(c)
type(shape)

#write a new function: chkshape(array), output -1 means error, 1 it is square, 0 it is rectangle.

def chkshape(array):
    if np.ndim(array) != 2:
        print("Error, the matrix is not 2-Dimension.")
        return -1
    else:
        shape = np.shape(array)
        if (shape[0]-shape[1]) == 0:
            return 1
        else: 
            return 0

print(chkshape(c))
print(chkshape(matrixA))

(3, 2)
0
1


In [10]:
#Check upper triangle matrix
ye = np.array([[1,-3,4],[0,1,2],[0,0,1]])
ye[0]
print(ye[1,1:])

for i in range (1,3):
    for j in range(0,i):
        if ye[i][j]!=0:
            print(False)
print (True)

#write a function to check the upper triangle property of any given matrix.
#Output: True as upper tirangle shape, False as not upper triangle shape.
# Learned from [https://www.geeksforgeeks.org/program-check-matrix-upper-triangular/]
def checkUpper(array):
    #after confirmation of being square matrix.
    dim = np.shape(ye)[0]
    for i in range(1,dim):
        for j in range(0,i):
            if array[i][j]!=0:
                return False
    return True
checkUpper(ye)
checkUpper(c)

[1 2]
True


NameError: name 'c' is not defined

In [101]:
shape = np.shape(ye)
shape[0]
type(ye[0])
aug = np.append(ye[0],1)
type(aug)

numpy.ndarray

In [112]:
vetA = np.transpose(np.array([7,2,5]))
np.shape(vetA)[0]
np.shape(ye)[1]

3

In [13]:
# Make a function to make augmented matrix. UNFINISHED
# Input matrix of shape m*n, vector of size m*1.
def augment(array,vector):
    #Need to create a new matrix a new matrix.
    rows = np.shape(vector)[0]
    matCols = np.shape(array)[1]
    for i in range(rows):
        aug = np.append(array[i],vector[i])
        print(aug)
    return aug
print(augment(ye,vetA))


[ 1 -3  4  1]
[ 0  1  2 -3]
[0 0 1 5]


IndexError: index 3 is out of bounds for axis 0 with size 3

In [29]:
# Compute the variable from last row upperward.
def backsub(array,vector):
    #Start to iterate from the bottom row, get the last entry's value.
    #Find the last index's value of vector.
    #compute the result of x(index).
    #Then go up one row. compute the result of x(index) by using what is stored in the result list(?).
    #Every time you compute you need to iterate the result list, may not necessary. 
    #And the result list size is fixed in the beginning. 
    ls = np.zeros_like(vector)
    size = np.shape(vector)[0]
    
    for i in range(size-1,-1,-1): #index starts from n-1 to 0.
        if i == size - 1:
            x = (vector[i])/array[-1,-1]
        else:
            x = (vector[i]-np.sum(array[i,i:] * ls[i+1:]))/array[i,i]
        ls[i]=x
    print(ls)
backsub(ye,vetA)

print(np.shape(ye)[0])

[-12 -14  -1   6]
3


In [23]:
import numpy as np
for i in range(10,0,-1):
    print(i)
tup = (3,)
print(type(tup))
lss = list()
type(lss)
vetA =[1,-3,5,6]
a =np.zeros_like(vetA)
a
ye
print(np.shape(ye))

10
9
8
7
6
5
4
3
2
1
<class 'tuple'>
(3, 3)


## Start of Homework Answer
### Question A
Familiarize yourself with the numpy.linalg package. Define a 10 × 10 matrix A whose entries are
the numbers from 1 to 100 ordered consecutively going across rows (so a1,1 = 1, a2,1 = 11, a10,1 = 91,
etc). Let v = (1, 2, ...10), and b = (1, 1, ...1). Compute Av and solve Ax = b and Ax = v using
linalg.solve. Verify your solution by computing Ax.

In [38]:
#CREATE A 10 BY 10 MATRIX CALLED matrixA
import numpy as np

matrixA=np.arange(1,101,1).reshape(10,10)

#DEFINE VECTOR V AND B
v = np.arange(1,11)
b = np.ones(10)

#SHOW THE SHAPE OF A,V,B.
print("matrix A is\n",matrixA)
print("vector v and b are:\n",v,' ;',b)

#COMPUTE THE Av
Av = np.dot(matrixA,v)
print("The result of Av is:\n",Av)

#SOLVE THE AX=B AND AX=V.
x1 = np.linalg.solve(matrixA,b)
x2 = np.linalg.solve(matrixA,v)

print(np.dot(matrixA,x1))
print(np.dot(matrixA,x2))

matrix A is
 [[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
vector v and b are:
 [ 1  2  3  4  5  6  7  8  9 10]  ; [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
The result of Av is:
 [ 385  935 1485 2035 2585 3135 3685 4235 4785 5335]


LinAlgError: Singular matrix

### Question B
You may get some error in doing above. You decide to “shake” your matrix by some noise, after all data usual comes in noisy. Use the numpy.random package to build a 10×10 matrix R(ε) whose entries are i.i.d. Gaussian random variables that follow N(0,ε2). Verify now that you “can” compute the questions above for various values of ε > 0 for the new matrix A + R(ε).

In [55]:
#CONSTRUCT THE NOISE MATRIX
def R(echelon):
    mean = 0
    var = echelon**2
    matrixNoise = np.random.normal(mean,var,(10,10))
    return matrixNoise
matrixNoise = R(0.2)
print("The noise matrix is constructed by standard deviation of 0.2:\n",matrixNoise)

#COMBINE THE TWO MATRICES.
matrixNew = matrixNoise + matrixA

#SOLVE THE NEW MATRIX Ax=b and Ax=v.
x3 = np.linalg.solve(matrixNew,b)
x4 = np.linalg.solve(matrixNew,v)

#CHECK ANSWER.
print("The solution of matrix (A+R(eplison))x=b is:\n",np.dot(matrixNew,x3))
print("The solution of matrix (A+R(eplison))x=v is:\n",np.dot(matrixNew,x4))
print("The result shows that we could compute correctly now.")

The noise matrix is constructed by standard deviation of 0.2:
 [[ 2.71764793e-02 -2.08336508e-02  2.78202933e-02 -5.46889033e-02
  -3.71350703e-02  1.50234775e-03 -1.97215769e-02 -4.07138834e-02
   8.69306044e-02 -6.82837636e-02]
 [-3.96691495e-02  2.78860873e-02 -2.60674607e-02  1.78651358e-02
  -8.23215472e-02  3.31391412e-02  1.43674672e-02 -5.43387868e-02
  -5.43244001e-02  1.76813709e-02]
 [-6.25942492e-02 -6.18241290e-02 -1.47378651e-02 -4.81583737e-02
   5.37074563e-02  2.53549850e-02  8.42243603e-03 -4.60951955e-04
   2.84062548e-03 -4.49499548e-02]
 [ 1.11928426e-01 -2.30674376e-02  6.43515000e-03 -1.91448556e-02
  -8.15028579e-03  7.84613997e-02  4.57281328e-03  1.96265416e-02
   1.15964734e-03  6.80167442e-03]
 [ 6.60948695e-02  5.14630371e-02 -1.57815899e-02 -3.67997574e-02
   7.23687802e-03 -4.01968969e-02 -2.53598085e-02 -5.43334091e-02
  -1.26400654e-03  1.37078058e-02]
 [-3.34455458e-02  3.06927316e-02  9.57351260e-03  1.56404960e-02
  -5.55000919e-05 -3.60826632e-02 -1

### Question C
Write a python function BackSub(A, b) that does the backward substitution from scratch. The input A must be an upper triangular square matrix whose diagonals are all nonzero, and b must be a vector of appropriate dimension. Raise an error if inputs do not satisfy the requirements. Only 1 for loop is needed. It should return the unique solution of solving Ax = b. Test your function on
(a) Problem 3 (b) a 3 × 3 matrix that is not upper triangular (c) a 3 × 2 matrix (d) Problem 5

In [49]:
#PREPARE THE INPUT MATRIX
#(a)matrix and vector from Problem 3
matA = np.array([[1,-3,4],[0,1,2],[0,0,1]])
vetA = np.transpose(np.array([7,2,5]))

#(b)one lower triangle matrix
matB = np.array([[1,2,0],[0,2,4],[3,0,0]])

#(c)a 3*2 matrix
matC = np.array([[1,2],[3,5],[5,6]])

#(d)matrix and vector from Problem 5.
matD = np.array([[1,-3,7],[0,1,4],[0,0,0]])
vetD = np.array([1,0,5])

def chkshape(array):
    #write a new function: chkshape(array), output -1 means error, 1 it is square, 0 it is rectangle.
    if np.ndim(array) != 2:
        print("Error, the matrix is not 2-Dimension.")
        return -1
    else:
        shape = np.shape(array)
        if (shape[0]-shape[1]) == 0:
            return 1
        else: 
            return 0

        
def checkUpper(array):
    #write a function to check the upper triangle property of any given matrix.
    #Output: True as upper tirangle shape, False as not upper triangle shape.
    #Learned from [https://www.geeksforgeeks.org/program-check-matrix-upper-triangular/]
    #after confirmation of being square matrix.
    dim = np.shape(ye)[0]
    for i in range(1,dim):
        for j in range(0,i):
            if array[i][j]!=0:
                return False
    return True
        
# Compute the variable from last row upperward.
def backsub(array,vector):
    if chkshape(array) !=1:
        if chkshape(array) == 0:
            print("Error message: Matrix\n",array," \nis rectangle. ")
            return
    else:
        if checkUpper(array) == False:
            print("error message: Matrix shape is not uppertriangle.\n","Please reenter your matrix")
            return
    #Start to iterate from the bottom row, get the last entry's value.
    #Find the last index's value of vector.
    #compute the result of x(index).
    #Then go up one row. compute the result of x(index) by using what is stored in the result list(ls).
    #Learned from [https://codereview.stackexchange.com/questions/110039/back-substitution-method-for-solving-linear-system]
    ls = np.zeros_like(vector)
    size = np.shape(vector)[0]
    
    for i in range(size-1,-1,-1): #index starts from n-1 to 0.
        if array[i,i] == 0:
            print("error message: the diagonal entries has zero in it.")
            return
        if i == size - 1:
            x = (vector[i])/array[-1,-1]
        else:
            x = (vector[i]-np.sum(array[i,i+1:] * ls[i+1:]))/array[i,i]
        ls[i]=x
    print(ls)
#The linear system in (a) works fine.
backsub(matA,vetA)
#The linear system in (b) is not a square matrix.
backsub(matB,vetA)
#The shape of linear system in (C) is not right.
backsub(matC,vetA)
#The zero diagonal entry in matrix (D) prevent the calculation success.
backsub(matD,vetD)

[-37  -8   5]
error message: Matrix shape is not uppertriangle.
 Please reenter your matrix
Error message: Matrix
 [[1 2]
 [3 5]
 [5 6]]  
is rectangle. 
error message: the diagonal entries has zero in it.
